export enum EHSPermissionDefination {
    dashboardCreate = 'create',
    dashboardRead = 'read',
    dashboardUpdate = 'update',
    divsionMasterCreate = 'create-division',
    divsionMasterRead = 'read-division',
    divsionMasterUpdate = 'update-division',
    divsionMasterDelete = 'delete-division',
    divsionMasterList = 'list-division',
    employeeMasterCreate = 'create-employee',
    employeeMasterRead = 'read-employee',
    employeeMasterUpdate = 'update-employee',
    employeeMasterDelete = 'delete-employee',
    employeeMasterList = 'list-employee',

    // AddLead = 'add-lead',
    // EditLead = 'edit-lead',
    // ViewLead = 'view-lead',
    // AddProuct = 'add-product',
    // EditProduct = 'edit-product',
    // ViewProduct = 'view-product',
    // AddUser = 'add-user',
    // EditUser = 'edit-user',
    // ViewUser = 'view-user',
    // AddRole = 'add-role',
    // EditRole = 'edit-role',
    // ViewRole = 'view-role',
    // ListLead = 'list-lead',
    // ListCustomer = 'list-customer',
    // ListProduct = 'list-product',
    // ListUser = 'list-user',
    // ListRole = 'list-role',
    // ListFollowUpAction = 'list-follow-up-action',
    // AddFollowUpAction = 'add-follow-up-action',
    // EditFollowUpAction = 'edit-follow-up-action',
    // ViewFollowUpAction = 'view-follow-up-action',
    // ListOrder = 'list-order',
    // AddOrder = 'add-order',
    // EditOrder = 'edit-order',
    // ViewOrder = 'view-order',
    // ListQuotation = 'list-quotation',
    // AddQuotation = 'add-quotation',
    // EditQuotation = 'edit-quotation',
    // ViewQuotation = 'view-quotation',
    // ListTicket = 'list-ticket',
    // AddTicket = 'add-ticket',
    // EditTicket = 'edit-ticket',
    // ViewTicket = 'view-ticket',
    // ActivityPlanner = 'activity-plannar',
    // UpdateRoleUsres = 'update-role-users',
    // AssignLead = 'assign-lead',
}

export enum CRMRoleDefination {
    Admin = 'Admin',
    SuperAdmin = 'SuperAdmin',
    NSM = 'NSM',
    RSM = 'RSM',
    ZSM = 'ZSM',
    ASM = 'ASM',
    SalesExecutive = 'SalesExecutive',
    Customerlist = 'Customer list',
    ProductConsultant = 'ProductConsultant',
    AdminSupport = 'Admin Support',
    Account = 'Account',
    SupportUser = 'SupportUser',
    PurchaseAndSaleRole = 'Purchase and sale role',
}
